export {default as Login} from './Login'
export {default as Signup} from './Signup'
export {default as Dashboard} from './Dashboard'
export {default as ResetPassword} from './ResetPassword'
export {default as ConfirmPassword} from './ConfirmPassword'
export {default as ApplyLoan} from './ApplyLoan'